// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZHXg4N8SGdFrWt2oD_ZdkIePhzy6BA0k',
    appId: '1:1037076257207:web:2eedae07225acf7b19b032',
    messagingSenderId: '1037076257207',
    projectId: 'uk-restaurant-staff',
    authDomain: 'uk-restaurant-staff.firebaseapp.com',
    storageBucket: 'uk-restaurant-staff.appspot.com',
    measurementId: 'G-91MD28Q2SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClQsIj9UYgdbRrk5dLiLCtgnvr4m99d4c',
    appId: '1:1037076257207:android:0891ee34712738a919b032',
    messagingSenderId: '1037076257207',
    projectId: 'uk-restaurant-staff',
    storageBucket: 'uk-restaurant-staff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBguXS7qUvgC-splVrmNAyjNmOb_OSa4Is',
    appId: '1:1037076257207:ios:d4e19f8be404755019b032',
    messagingSenderId: '1037076257207',
    projectId: 'uk-restaurant-staff',
    storageBucket: 'uk-restaurant-staff.appspot.com',
    androidClientId: '1037076257207-p92buvi0pvpri2b51ueb982sf4s55u84.apps.googleusercontent.com',
    iosBundleId: 'franchose.restaurantstaff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBguXS7qUvgC-splVrmNAyjNmOb_OSa4Is',
    appId: '1:1037076257207:ios:70f5a352694feb6719b032',
    messagingSenderId: '1037076257207',
    projectId: 'uk-restaurant-staff',
    storageBucket: 'uk-restaurant-staff.appspot.com',
    androidClientId: '1037076257207-p92buvi0pvpri2b51ueb982sf4s55u84.apps.googleusercontent.com',
    iosBundleId: 'com.example.manolo',
  );
}
